name: Hosts

on:
  push:
    paths: "hosts/**"
    branches: [main]

permissions:
  contents: write

jobs:
  runCommands:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@cd7d8d697e10461458bc61a30d094dc601a8b017
      - name: Import GPG key
        uses: crazy-max/ghaction-import-gpg@01dd5d3ca463c7f10f7f4f7b4f177225ac661ee4
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.PASSPHRASE }}
          git_user_signingkey: true
          git_commit_gpgsign: true
      - name: Sign commit and push changes
        run: |
          cp hosts/hosts.txt hosts/zero/hosts.txt
          sed -i -b 's/127\.0\.0\.1/0\.0\.0\.0/g' hosts/zero/hosts.txt
          git add .
          git commit -S -m "Update hosts.txt"
          git push
